# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-31 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='NAME')),
                ('description', models.CharField(max_length=32, verbose_name='NAME')),
                ('date', models.DateTimeField(verbose_name='DATE')),
            ],
            options={
                'db_table': 'Commit',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='NAME')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crawler.User'),
        ),
    ]
